random:
  seed: 42
dataset:
  descriptions: ".descriptions.txt"
  subset: "v0"
tokenizer:
  name: "bert-base-uncased"
datamodule:
  batch_size: 2
model:
  text_encoder:
    name: "bert-base-uncased"
  label_encoder:
    name: "bert-base-uncased"
optimizer:
  args:
    lr: 3e-5
trainer:
  gpus: 1
  progress_bar_refresh_rate: 25
  max_epochs: 5
  deterministic: True
  val_check_interval: 0.25
  num_sanity_val_steps: 0
  accumulate_grad_batches: 4
checkpoint_path: "./checkpoints/{epoch}"